### ISSUE TITLE
"Unhandled SetProperty type ObjectProperty" while parsing a save with sav_parse.py

### ISSUE THREAD

**Issue by Buggy123** [GreyHak/sat_sav_parse#2]
You requested that I post this error here. While parsing the save with sav_parse.py via command line, it fails while parsing the save.
OS is Linux, with the latest version of Python.

```
Traceback (most recent call last):
  File "/home/buggy/Documents/satisfactory_save_stuff/sat_sav_parse-main/sav_parse.py", line 3613, in <module>
    (saveFileInfo, headhex, grids, levels, extraMercerShrineList) = readFullSaveFile(savFilename, decompressedOutputFilename)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buggy/Documents/satisfactory_save_stuff/sat_sav_parse-main/sav_parse.py", line 3535, in readFullSaveFile
    (offset, level) = parseLevel(offset, data, True, progressBar) # Potentially sets the global satisfactoryCalculatorInteractiveMapFlag
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buggy/Documents/satisfactory_save_stuff/sat_sav_parse-main/sav_parse.py", line 2955, in parseLevel
    offset = object.parse(offset, data, actorAndComponentObjectHeaders[idx])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buggy/Documents/satisfactory_save_stuff/sat_sav_parse-main/sav_parse.py", line 2595, in parse
    (offset, self.properties, self.propertyTypes) = parseProperties(offset, data)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/buggy/Documents/satisfactory_save_stuff/sat_sav_parse-main/sav_parse.py", line 3089, in parseProperties
    raise ParseError(f"Unhandled SetProperty type {type}")
ParseError: Unhandled SetProperty type ObjectProperty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/buggy/Documents/satisfactory_save_stuff/sat_sav_parse-main/sav_parse.py", line 3730, in <module>
    raise Exception(f"ERROR: While processing '{savFilename}': {error}")
Exception: ERROR: While processing '../Completed.sav': Unhandled SetProperty type ObjectProperty
```

**Comment by GreyHak** [comment]
@Buggy123 In order to parse a new "ObjectProperty" I would need a sample save file that contains it as I would need to review the binary data to determine the format of the property.  Could you please attach one?  Thank you.

**Comment by GreyHak** [comment]
Support for the SetProperty type ObjectProperty added.  Thank you for sharing your save file.
