### ISSUE TITLE
[INVALID] TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by Quix0r** [GreyHak/sat_sav_parse#5]
```
$ python3 ./sav_cli.py --from-json test.json ~/Nextcloud/Others/Save-Games/Satisfactory/FactoryGame/Saved/SaveGames/76561197967870139/235\ -\ Production\ of\ OC\ Supercomputer\ started2.sav
Reading JSON
Parsing JSON
Writing Save
Traceback (most recent call last):####################################################]   4215/4245
  File "/.../sat_sav_parse/./sav_cli.py", line 644, in <module>
    sav_to_resave.saveFile(saveFileInfo, headhex, grids, levels, extraObjectReferenceList, outFilename)
  File "/.../sat_sav_parse/sav_to_resave.py", line 737, in saveFile
    data.extend(addLevel(level))
                ^^^^^^^^^^^^^^^
  File "/.../sat_sav_parse/sav_to_resave.py", line 693, in addLevel
    dataObj.extend(addObject(objects[idx], actorAndComponentObjectHeaders[idx]))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../sat_sav_parse/sav_to_resave.py", line 508, in addObject
    (source, target) = object.actorSpecificInfo
    ^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../sat_sav_parse/./sav_cli.py", line 649, in <module>
    raise Exception(f"ERROR: While validating save to '{outFilename}': {error}")
Exception: ERROR: While validating save to '/home/quix0r/Nextcloud/Others/Save-Games/Satisfactory/FactoryGame/Saved/SaveGames/76561197967870139/235 - Production of OC Supercomputer started2.sav': cannot unpack non-iterable NoneType object
$
```

**Comment by Quix0r** [comment]
Example:
```json
        {
          "instanceName": "Persistent_Level:PersistentLevel.BP_DebrisActor_02_C_11836",
          "objectGameVersion": 46,
          "smortpFlag": false,
          "actorReferenceAssociations": {
            "parentObjectReference": {
              "levelName": "",
              "pathName": ""
            },
            "actorComponentReferences": []
          },
          "properties": [],
          "propertyTypes": [],
          "actorSpecificInfo": null
        },
```
It's root JSON node is a code: `AYA5Y3Y4QXOR0ZIGYI7IA16CF` which has `levels` as its own root.

EDIT: All debris-relevant JSON nodes have `"actorSpecificInfo": null` set!

EDIT2: Yes, I have Christmas lights added to some power lines. So the above JSON is not matching with the error message.

**Comment by Quix0r** [comment]
This issue does not happen with an older save-game (same mods, just lesser progress). When issue #6 is fixed, then I retest this one and close when it doesn't happen again.

**Comment by Quix0r** [comment]
Issue has been fixed.
