### ISSUE TITLE
sav_parse.ParseError: Unsupported ArrayProperty type 'TextProperty'

### ISSUE THREAD

**Issue by Quix0r** [GreyHak/sat_sav_parse#6]
I get this message with a more recent save-game (the older one is now working but I like to keep the other issue open if that error is also gone with a more recent version.

The error message happens with this (modded) save-game:
[modded-satisfactory-game.sav.gz](https://github.com/user-attachments/files/18205861/modded-satisfactory-game.sav.gz)

```
$ python3 ./sav_cli.py --to-json ~/.local/share/Steam/steamapps/compatdata/526870/pfx/drive_c/users/steamuser/AppData/Local/FactoryGame/Saved/SaveGames/76561197967870139/243\ -\ Walked\ around\ \(save\ due\ to\ bug\).sav test.json 
Decompression: [######################################################################] ✓ 12325278/12325278
Traceback (most recent call last):###################.................................]   220131/422168
  File "/.../sat_sav_parse/./sav_cli.py", line 535, in <module>
    (saveFileInfo, headhex, grids, levels, extraObjectReferenceList) = sav_parse.readFullSaveFile(savFilename)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../sat_sav_parse/sav_parse.py", line 3624, in readFullSaveFile
    (offset, level) = parseLevel(offset, data, True, progressBar) # Potentially sets the global satisfactoryCalculatorInteractiveMapExtras
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../sat_sav_parse/sav_parse.py", line 2973, in parseLevel
    offset = object.parse(offset, data, actorAndComponentObjectHeaders[idx])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../sat_sav_parse/sav_parse.py", line 2602, in parse
    (offset, self.properties, self.propertyTypes) = parseProperties(offset, data)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../sat_sav_parse/sav_parse.py", line 3289, in parseProperties
    raise ParseError(f"Unsupported ArrayProperty type '{arrayType}'")
sav_parse.ParseError: Unsupported ArrayProperty type 'TextProperty'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../sat_sav_parse/./sav_cli.py", line 555, in <module>
    raise Exception(f"ERROR: While processing '{savFilename}': {error}")
Exception: ERROR: While processing '/home/quix0r/.local/share/Steam/steamapps/compatdata/526870/pfx/drive_c/users/steamuser/AppData/Local/FactoryGame/Saved/SaveGames/76561197967870139/243 - Walked around (save due to bug).sav': Unsupported ArrayProperty type 'TextProperty'
```

**Comment by GreyHak** [comment]
@Quix0r Added support for array type TextProperty.  Thank you for sharing your save file.

**Comment by Quix0r** [comment]
Commit id fd715e11725cc99996624076287344d5630ec22b has fixed the issue, thank you.
